# Generated by Django 4.0.4 on 2022-04-13 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='pub_comments', to='publications.comment', verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_pub', to='publications.publication', verbose_name='Публикация'),
        ),
    ]
