# Generated by Django 4.0.4 on 2022-04-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_comments_alter_comment_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication', verbose_name='Публикация'),
        ),
    ]
