# Generated by Django 4.0.4 on 2022-04-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_comment_path_comment_left_comment_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='position',
        ),
    ]
